version: '3.0'

services:
  jaeger:
    image: jaegertracing/jaeger-query:1.51
    container_name: 'jaeger-quickwit'
    environment:
      - GRPC_STORAGE_SERVER=host.docker.internal:7281
      - SPAN_STORAGE_TYPE=grpc-plugin
    ports:
      - 16686:16686
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - quickwit
  grafana:
    container_name: 'grafana-quickwit-datasource'
    build:
      context: ./.config
      args:
        grafana_version: 10.0.1
    ports:
      - 3000:3000/tcp
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-quickwit-datasource
      - ./provisioning:/etc/grafana/provisioning
      - gquickwit:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - quickwit

networks:
  quickwit:
    driver: bridge

volumes:
  gquickwit:
